[build]
# Specify the PHP version
NIXPACKS_PHP_VERSION = "8.4"
# Optional: Define a custom install command if needed
installCommand = "composer install --no-dev"

[deploy]
# Optional: Define a custom start command for your application
startCommand = "php artisan serve --port=$PORT"
